name: My script running

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"

permissions:
  id-token: write
  contents: read

jobs:
  script:
    runs-on: [self-hosted, homelab, nvidia]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run script
        run: python3 my_script.py
